[package]
name = "microwave"
version = "0.10.0"
authors = ["Woyten <woyten.tielesch@online.de>"]
description = "Make xenharmonic music and explore musical tunings."
repository = "https://github.com/Woyten/tune/tree/master/microwave"
readme = "README.md"
keywords = ["microtonal", "piano", "scales", "synthesizer", "tuning"]
license = "MIT"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
sf3 = ["fluidlite-lib/with-sf3"]

[dependencies]
chrono = "0.4.15"
cpal = { version = "0.12.1", features = ["wasm-bindgen"] }
hound = "3.4.0"
midir = "0.7.0"
structopt = "0.3.16"
tune = { version = "0.16.0", path = ".." }
tune-cli = { version = "0.13.0", path = "../tune-cli"}

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
nannou = { version = "0.14.1" }
fluidlite = { version = "0.1.3" }
fluidlite-lib = { version = "0.1.3" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.67"
web-sys = { version = "0.3.44", features = ["UrlSearchParams"] }
yew = "0.17.3"
