[package]
name = "tune-cli"
version = "0.13.0"
authors = ["Woyten <woyten.tielesch@online.de>"]
description = "Explore musical tunings and create synthesizer tuning files for microtonal scales."
repository = "https://github.com/Woyten/tune/tree/master/tune-cli"
readme = "README.md"
keywords = ["microtonal", "midi", "scales", "synthesizer", "tuning"]
license = "MIT"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "tune"
path = "src/main.rs"

[dependencies]
midir = "0.7.0"
serde = { version = "1.0.106", features = ["derive"] }
serde_json = "1.0.51"
structopt = "0.3.13"
tune = { version = "0.16.0", path = ".." }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.67"
yew = "0.17.3"